# Название среды и название кластера.
ClusterEnv: dev
ClusterName: test-app

# Namespace, в который устанавливаем кластер
namespace: tarantool

# docker образ, из которого создаем контейнеры
image:
  repository: myapp
  tag: 0.1.0-0-g47ec184
  pullPolicy: IfNotPresent

# Топология кластера включающает в себя описание количества
# и характеристик репликасетов и описывается в разделе RoleConfig

# Допустим, мы хотим создать кластер содержащий два типа репликасетов:
# routers и storages
RoleConfig:
  - RoleName: storages
    ReplicaCount: 1
    ReplicaSetCount: 3
    DiskSize: 1Gi
    CPUallocation: 0.1
    MemtxMemoryMB: 256
    RolesToAssign:
      - crud-storage
      - vshard-router
      - metrics
