apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Tarantool CRUD
name: crud-storage
version: 0.0.2
dependencies:
- name: tarantool-operator
  version: "0.0.6"
  repository: "https://tarantool.github.io/tarantool-operator"
