# Declare variables to be passed into your templates.

ClusterEnv: dev
ClusterName: tarantool-crud

image:
  repository: vasiliyt/tarantool-crud
  tag: 0.0.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

Prometheus:
  port: 8081
  path: /metrics

RoleConfig:
  - RoleName: storage
    ReplicaCount: 1
    ReplicaSetCount: 3
    DiskSize: 1Gi
    CPUallocation: 0.25
    MemtxMemoryMB: 256
    RolesToAssign:
      - crud-storage
      - vshard-router
      - metrics
      - migrator
